controllers:
    resource: ../src/Controller/
    type: attribute

redirect_to_login:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_login'